---
kind: PostgreToQdrantBronzeConfig
spec:
  extractor:
    kind: PostgreDBExtractorWithPolarsConfig
    spec:
      uri: postgresql://postgres:postgres@localhost:5432/market_data
      source_table_name: public.fs_financial_statistics_overview_type_four
      extractor_column_filter: is_load_to_qdrant
      filter_value: "0"
  transform:
    kind: QdrantTransformConfig
    spec:
      transform_steps:
        - kind: etl_pipeline.infrastructure.polars.etl.transform.columns.RenameColumns
          spec:
            column_mappings: 
              stock_id: "tên cổ phiếu"
              year: "năm"
              quarter: "quý"
              p_e: "Hệ số giá trên thu nhập p/e"
              p_s: "Hệ số giá trên doanh thu p/s"
              p_b: "Hệ số giá trên giá trị sổ sách p/b"
              eps: "Thu nhập trên mỗi cổ phiếu eps"
              net_profit_margin: "tỷ lệ lãi ròng (%)"
              yoea: "Tỷ suất sinh lời của tài sản sinh lãi yoea (%)"
              nim: "Tỷ lệ thu nhập lãi thuần nim (%)"
              cof: "Chi phí vốn cof"
              lar: "Tỷ lệ cho vay trên tổng tài sản lar"
              ldr: "Tỷ lệ dư nợ tín dụng trên vốn huy động ldr"
              clr: "Tỷ lệ khả năng chi trả cốt lõi clr"
              cta: "Tỷ lệ vốn trên tổng tài sản cta"
              elr: "Tỷ lệ vốn chủ sở hữu trên tổng dư nợ cho vay elr"
              roa: "Tỷ suất sinh lời trên tổng tài sản roa"
              roe: "Tỷ suất sinh lời trên vốn chủ sở hữu roe"
              cir: "Tỷ lệ chi phí trên thu nhập cir"
              llrl: "Tỷ lệ dự phòng rủi ro tín dụng trên tổng dư nợ llrl"
              llrnpl: "Tỷ lệ bao phủ nợ xấu llrnpl"
              npl_ratio: "Tỷ lệ nợ xấu npl_ratio"
              pcl: "Chi phí dự phòng rủi ro tín dụng pcl"
            
        - kind: etl_pipeline.infrastructure.polars.etl.transform.columns.ConcatColumns
          spec:
            concat_columns:
              - "tên cổ phiếu"
              - "năm"
              - "quý"
              - "Hệ số giá trên thu nhập p/e"
              - "Hệ số giá trên doanh thu p/s"
              - "Hệ số giá trên giá trị sổ sách p/b"
              - "Thu nhập trên mỗi cổ phiếu eps"
              - "tỷ lệ lãi ròng (%)"
              - "Tỷ suất sinh lời của tài sản sinh lãi yoea (%)"
              - "Tỷ lệ thu nhập lãi thuần nim (%)"
              - "Chi phí vốn cof"
              - "Tỷ lệ cho vay trên tổng tài sản lar"
              - "Tỷ lệ dư nợ tín dụng trên vốn huy động ldr"
              - "Tỷ lệ khả năng chi trả cốt lõi clr"
              - "Tỷ lệ vốn trên tổng tài sản cta"
              - "Tỷ lệ vốn chủ sở hữu trên tổng dư nợ cho vay elr"
              - "Tỷ suất sinh lời trên tổng tài sản roa"
              - "Tỷ suất sinh lời trên vốn chủ sở hữu roe"
              - "Tỷ lệ chi phí trên thu nhập cir"
              - "Tỷ lệ dự phòng rủi ro tín dụng trên tổng dư nợ llrl"
              - "Tỷ lệ bao phủ nợ xấu llrnpl"
              - "Tỷ lệ nợ xấu npl_ratio"
              - "Chi phí dự phòng rủi ro tín dụng pcl"
            new_column: chunk_content
        - kind: etl_pipeline.infrastructure.polars.etl.transform.columns.SelectColumns
          spec:
            columns:
              - id
              - tên cổ phiếu
              - năm
              - quý
              - chunk_content
        - kind: etl_pipeline.infrastructure.polars.etl.transform.columns.RenameColumns
          spec:
            column_mappings: 
              tên cổ phiếu: stock_id
              năm: year
              quý: quarter
        - kind: etl_pipeline.infrastructure.polars.etl.transform.columns.AddColumn
          spec:
            column: is_embedded
            value: 0
        - kind: etl_pipeline.infrastructure.polars.etl.transform.columns.AddColumn
          spec:
            column: document_type
            value: "financial_statistics"
  loader:
    kind: QdrantLoaderConfig
    spec:
      qdrant_url: http://qdrant:6333
      destination_collection_name: stock_price_embedded