---
kind: QdrantToQdrantSilverConfig
spec:
  extractor:
    kind: QdrantExtractorWithPayloadConfig
    spec:
      qrant_url: http://qdrant:6333
      collection_name: newspaper
      payload_filter: 
        is_embedded: 0
  transform:
    kind: QdrantTransformConfig
    spec:
      transform_steps:
        - kind: src.infrastructure.polars.etl.transform.example.ExampleTransformStep
        - kind: src.infrastructure.polars.etl.transform.columns.SelectColumns
          spec:
            columns:
              - id
              - newspaper_content
        - kind: src.infrastructure.polars.etl.transform.clean_text.CleanTextPolars
          spec:
            col_name: newspaper_content
        - kind: src.infrastructure.polars.etl.transform.chunking.ChunkPolars
          spec:
            document_col_name: newspaper_content
            chunk_col_name: chunk_content
            splitter_type: recursive_character
            chunk_size: 1200
            chunk_overlap: 300
        - kind: src.infrastructure.polars.etl.transform.embedding.TextEmbedding
          spec:
            embedding_type: google_embedding
            model: gemini-embedding-2
            task_type_documents: RETRIEVAL_DOCUMENT
            task_type_query: RETRIEVAL_QUERY
            output_dimensionality: 768
            batch_size: 100
            text_column: chunk_content
            output_column: chunk_embedded
  loader:
    kind: QdrantLoaderConfig
    spec:
      qrant_url: http://qdrant:6333
      collection_name: newspaper_embedded
      qrant_payload: 
        id: str
        document_id: str
        chunk_content: str
        chunk_index: int