---
kind: QdrantToQdrantSilverConfig
spec:
  loader:
    kind: QdrantExtractorWithPayloadConfig
    spec:
      qrant_url: http://qdrant:6333
      collection_name: newspaper
      payload_filter: 
        is_load_to_qdrant: 0
  transformer:
    kind: QdrantTransformConfig
    spec:
      transform_steps:
        - kind: src.infrastructure.polars.etl.transform.example.ExampleTransformStep
        - kind: src.infrastructure.polars.etl.transform.clean_text.CleanTextPolars
  extractor:
    kind: QdrantExtractorWithPayloadConfig
    spec:
      qrant_url: http://qdrant:6333
      collection_name: newspaper
      payload_filter:
        is_load_to_qdrant: 0
