---
kind: PostgreToBqSilverConfig
spec:
  extractor: 
    kind: PostgreDBExtractorWithPolarsConfig
    spec:
      query: 
        SELECT id::text AS id,
          fund_id,
          stock_id,
          business_sector,
          gav,
          month
        FROM public.fund_gav
      uri: "postgresql://postgres:postgres@localhost:5432/postgres" #Update here
  loader: 
    kind: BigQueryLoaderPolarsConfig
    spec:
      gcp_credential_key: ""
      project: "rich-finance-2026"
      dataset: "market_data"
      table: "fund_gav"
      write_disposition: "WRITE_TRUNCATE"
      enable_delete_before_load: false
