---
kind: PostgreToBqSilverConfig
spec:
  extractor:
    kind: PostgreDBExtractorWithPolarsConfig
    spec:
      uri: postgresql://postgres:postgres@localhost:5432/market_data
      query: |
        SELECT 
          id::text AS id,
          stock_id,
          trading_date,
          open_price,
          high_price,
          low_price,
          close_price,
          volume
        FROM public.stock_price
  loader:
    kind: BigQueryLoaderPolarsConfig
    spec:
      gcp_credential_key: gcp_sa_for_bq_data_append
      project: rich-finance-2026
      dataset: market_data
      table: stock_price
      write_disposition: WRITE_TRUNCATE
      enable_delete_before_load: true
