---
kind: PostgreToQdrantBronzeConfig
spec:
  extractor:
    kind: PostgreDBExtractorWithPolarsConfig
    spec:
      uri: postgresql://postgres:postgres@localhost:5432/market_data
      source_table_name: public.newspaper
      extractor_column_filter: is_load_to_qdrant
      filter_value: "0"
  transform: 
    kind: QdrantTransformConfig
    spec:
      transform_steps:
        - kind: etl_pipeline.infrastructure.polars.etl.transform.columns.RemoveColumn
          spec:
            column: is_load_to_qdrant
        - kind: etl_pipeline.infrastructure.polars.etl.transform.columns.AddColumn
          spec:
            column: is_embedded
            value: 0
        - kind: etl_pipeline.infrastructure.polars.etl.transform.columns.AddColumn
          spec:
            column: is_topic_tagging
            value: 0
  loader:
    kind: QdrantLoaderConfig
    spec:
      qdrant_url: http://qdrant:6333
      destination_collection_name: newspaper
      qdrant_payload: 
        id: str
        newspaper_title: str
        newspaper_url: str
        publish_date: Optional[date]
        newspaper_content: str
        newspaper_summary: str
        is_embedded: int
        created_at: date
        is_topic_tagging: int
  