---
kind: DagDefinition
metadata:
  name: 2026_06_10_newspapers_bronze
spec:
  dag_id: 2026_06_10_newspapers_bronze
  schedule: None
  start_date: 2023-01-01
  catchup: False
  default_args:
    owner: tuongnguyen
    retries: 5
    on_failure_callback: []
  tags: ["Bronze", "Newspaper"]
  task_factories:
    - id: job
      factory_type: BronzePostgreQdrantFactory
      args:
        task_id: "bronze_newspaper"
        job_config_path: /opt/airflow/dags/etl_pipeline_dags/src/config/postgre_to_qdrant/newspaper/bronze_newspaper.yaml
