---
kind: DagDefinition
metadata:
  name: 2026_07_18_fs_balance_sheet_type_one_qdrant_bronze
spec:
  dag_id: 2026_07_18_fs_balance_sheet_type_one_qdrant_bronze
  schedule: None
  start_date: 2026-07-14
  catchup: False
  default_args:
    owner: tuongnguyen
    retries: 5
    on_failure_callback: []
  tags: ["Silver", "Finance Statement", "Balance Sheet", "Type One", "Qdrant"]
  task_factories:
    - id: job
      factory_type: BronzePostgreQdrantFactory
      args:
        task_id: "bronze_fs_balance_sheet_type_one"
        job_config_path: /opt/airflow/dags/etl_pipeline_dags/src/config/postgre_to_qdrant/finance_statement/balance_sheet/bronze_fs_balance_sheet_type_one.yaml
