---
kind: DagDefinition
metadata:
  name: 2027_07_17_stock_price_silver
spec:
  dag_id: 2027_07_17_stock_price_silver
  schedule: None
  start_date: 2023-01-01
  catchup: False
  default_args:
    owner: tuongnguyen
    retries: 5
    on_failure_callback: []
  tags: ["Silver", "Stock Price", "Qdrant"]
  task_factories:
    - id: job
      factory_type: SilverQdrantEmbeddingTaskFactory
      args:
        task_id: "silver_qdrant_embedding"
        job_config_path: /opt/airflow/dags/etl_pipeline_dags/src/config/postgre_to_qdrant/stock_price/silver_stock_price.yaml
