---
kind: DagDefinition
metadata:
  name: 2026_06_10_newspapers_silver
spec:
  dag_id: 2026_06_10_newspapers_silver
  schedule: None
  start_date: 2023-01-01
  catchup: False
  default_args:
    owner: tuongnguyen
    retries: 5
    on_failure_callback: []
  tags: ["Silver", "Newspaper"]
  task_factories:
    - id: job
      factory_type: SilverNewspaperTaskFactory
      args:
        task_id: "silver_newspaper"
        job_config_path: /opt/airflow/dags/etl_pipeline_dags/src/config/postgre_to_qdrant/newspaper/silver_newspaper.yaml