---
kind: QdrantToQdrantSilverConfig
spec:
  extractor:
    kind: QdrantExtractorWithPayloadConfig
    spec:
      qdrant_url: http://qdrant:6333
      collection_name: stock_price_embedded
      payload_filter: 
        is_embedded: 0
  transform:
    kind: QdrantTransformConfig
    spec:
      transform_steps:
        - kind: etl_pipeline.infrastructure.polars.etl.transform.example.ExampleTransformStep
        - kind: etl_pipeline.infrastructure.polars.etl.transform.text_processing.tokenize_vi.TokenizeVi
          spec:
            col_name: chunk_content
            tokenize_col_name: chunk_content_vi_tokenized
        - kind: etl_pipeline.infrastructure.polars.etl.transform.embedding.SparseTextEmbedding
          spec:
            embedding_type: sparse_embedding
            model_name: Qdrant/bm25
        - kind: etl_pipeline.infrastructure.polars.etl.transform.embedding.TextEmbedding
          spec:
            embedding_type: google_embedding
            model: gemini-embedding-2
            task_type_documents: RETRIEVAL_DOCUMENT
            task_type_query: RETRIEVAL_QUERY
            output_dimensionality: 768
            batch_size: 100
            text_column: chunk_content
            output_column: dense_vector_embedded
            number_of_small_dataframes: 8
        - kind: etl_pipeline.infrastructure.polars.etl.transform.columns.AddColumn
          spec:
            column: is_embedded
            value: 1

  loader:
    kind: QdrantLoaderConfig
    spec:
      qdrant_url: http://qdrant:6333
      destination_collection_name: stock_price_embedded 
      is_upsert_source_table: false
      source_name: stock_price_embedded
      # qdrant_payload_for_source_table:
      #   is_embedded: 1
      # payload_filter_for_source_table:
      #   is_embedded: 0
