---
kind: PostgreToBqSilverConfig
spec:
  extractor:
    kind: PostgreDBExtractorWithPolarsConfig
    spec:
      uri: postgresql://postgres:postgres@localhost:5432/market_data
      source_table_name: public.stock_price
      enable_execution_date: true
      filter_type: date 
      filter_time_range: 90    
  transform:
    kind: QdrantTransformConfig
    spec:
      transform_steps: 
      - kind: etl_pipeline.infrastructure.polars.etl.transform.columns.RemoveColumn
        spec:
          column: is_load_to_qdrant
  loader:
    kind: BigQueryLoaderPolarsConfig
    spec:
      gcp_credential_key: gcp_sa_for_bq_data_append
      project: rich-finance-2026
      dataset: market_data
      table: stock_price
      write_disposition: WRITE_APPEND
      enable_delete_before_load: true
