---
kind: DagDefinition
metadata:
  name: market_data_stock_price
spec:
  dag_id: market_data_stock_price
  schedule: "0 0 * * *"
  start_date: 2023-01-01
  catchup: False
  default_args:
    owner: tuongnguyen
    retries: 5
    on_failure_callback: []
  tags: ["market_data", "stock_price"]
  task_factories:
    - id: job
      factory_type: SilverMarketDataTaskFactory
      args:
        task_id: "market_data_stock_price"
        job_config_path: /opt/airflow/dags/etl_pipeline_dags/src/config/postgre_to_bq/market_data/stock_price.yaml
