---
kind: DagDefinition
metadata:
  name: trigger_newspaper
spec:
  dag_id: trigger_newspaper
  schedule: "0 0 * * *"
  start_date: 2023-01-01
  catchup: False
  default_args:
    owner: tuongnguyen
    retries: 5
    on_failure_callback: []
  tags: ["newspaper", "bronze_layer"]
  task_factories:
    - id: job
      factory_type: TriggerDagsFactory
      args:
        task_id: "trigger_newspaper"
        job_config_path: /opt/airflow/dags/etl_pipeline_dags/src/config/trigger_dag/trigger_newspaper.yaml
